#use_frameworks!  如果使用use_frameworks  dynamic framework
#不使用 则以static library方式

platform :ios, '8.0'

target 'LBNetRequest_Example' do
  pod 'LBNetRequest', :path => '../'

  pod 'AFNetworking', '3.2.0'
  pod 'LBBaseTools', '0.1.0'
end

